# Generated by Django 4.0.3 on 2022-04-12 08:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_roll_no_student_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.IntegerField(auto_created=uuid.UUID('ef913390-07c9-4eb2-9958-ba9747e2e642'), primary_key=True, serialize=False),
        ),
    ]
